blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView
from django.conf import settings
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [
                  path('create/', BlogCreateView.as_view(), name='create'),
                  path('', BlogListView.as_view(), name='list'),
                  path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
                  path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
                  path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='index')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

blog/models.py
from django.db import models


# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name='заголовок')
    slug = models.CharField(max_length=250, verbose_name='slug', blank=True, null=True)
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', blank=True, null=True)
    date_create = models.DateTimeField(verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    view_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from blog.models import Blog
from pytils.translit import slugify


# Create your views here.
class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'date_create',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'date_create',)

    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <h2>Хотите удалить материал? "{{ object|title }}"</h2>
                        <button type="submit" class="btn btn-success">
                            Подтвердить

                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}


    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }} ({{ object.slug }})</h4>
                        {#                        <img src="{{ object.image|mediapath }}" width="100" height="100" alt="">#}
                    </div>

                    <div class="card-body">
                        <img src="{{ object.preview }}" width="100" height="100" alt="">
                        <p>{{ object.content }}...</p>
                        <p>Дата создания: {{ object.date_create }}</p>
                        <p>Количество просмотров: {{ object.view_count }}</p>

                    </div>

                </div>

            </div>
        </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}

                        </button>

                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ title }}</h1>
    </div>
    <p><a href="{% url 'blog:create' %}"
          class="btn btn-sm btn-success">Добавить статью</a>
    </p>
    <div class="row">
        {% for object in object_list %}
            <div class="col-6">

                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal"><a
                                href="{% url 'blog:view' object.pk %}">{{ object.title }}</a></h4>


                    </div>

                    <div class="card-body">
                        <img src="{{ object.preview }}" width="100" height="100" alt="">
                        <p>Краткое описание статьи: <br>{{ object.content|slice:100 }}...</p>
                        <p>Дата создания: {{ object.date_create }}</p>

                        <p>{{ object.description|slice:100 }}</p>
                        <p><a href="{% url 'blog:view' object.pk %}">Подробнее...</a></p>
                        <a href="{% url 'blog:edit' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}"
                           class="btn btn-sm btn-outline-secondary">Delete</a>

                    </div>

                </div>

            </div>
        {% endfor %}
    </div>

{% endblock %}