blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogUpdateView, BlogDetailView, BlogDeleteView
from django.conf import settings
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [
                  path('create/', BlogCreateView.as_view(), name='create'),
                  path('', BlogListView.as_view(), name='list'),
                  path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
                  path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
                  path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='index')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, verify_email, generate_new_password


app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/<str:uidb64>/<str:token>/', verify_email, name='verify_email'),
    path('profile/genpassword', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=40, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
from django.views.generic import CreateView, UpdateView
from django.core.mail import send_mail
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.html import strip_tags
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from config import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
import logging

logger = logging.getLogger('users')


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    # success_url = reverse_lazy('users:user_verify')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False  # Деактивируем пользователя

        # Сохраняем пользователя
        user.save()

        # Генерируем токен для верификации почты

        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)

        # Создаем URL для верификации

        current_site = get_current_site(self.request)
        verification_url = reverse('users:verify_email', kwargs={'uidb64': uid, 'token': token})
        verification_url = f'http://{current_site.domain}{verification_url}'

        # Формируем тему и текст письма

        subject = 'Интернет-магазин: подтверждение почты'
        message = render_to_string('users/email_verification.html', {
            'user': user,
            'verification_url': verification_url,
        })
        plain_message = strip_tags(message)

        # Отправляем письмо для верификации
        send_mail(
            subject=subject,
            message=plain_message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            html_message=message,
        )

        user.save()
        return render(self.request, 'users/registration_email_sent.html')


def verify_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

        logger.debug(f'Verifying email for user: {user.username}')

        if default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)  # Вход пользователя после активации
            messages.success(request, 'Почта подтверждена, вы вошли в систему.')
            return redirect('users:profile')  # Перенаправить на страницу профиля
        else:
            messages.error(request, 'Ссылка для подтверждения почты недействительна.')
            return redirect('users:login')  # Перенаправить на страницу входа
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    return redirect('users:login')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Смена пароля',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()

    return redirect(reverse('catalog:list'))

users/templates/users/email_verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <p>Здравствуйте!</p>
                        <p>Для подтверждения вашей почты, пожалуйста, перейдите по следующей ссылке:</p>
                        <p><a href="{{ verification_url }}">Подтвердить почту</a></p>
                    </form>
                </div>
                <div class="card-footer"></div>

            </div>
        </div>

    </div>

</body>
</html>

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Авторизация пользователя</div>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-success">Войти</button>
                    </div>
                </div>
            </div>

        </form>

    </div>


{% endblock %}

users/templates/users/profile.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Профиль пользователя</div>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </div>
            </div>

        </form>
        <div class="card-footer">
            <a href="{% url 'users:generate_new_password' %}" class="btn btn-outline-danger">Сгенерировать пароль</a>
        </div>

    </div>


{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Регистрация пользователя</div>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}

                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                    </div>
                </div>
            </div>

        </form>

    </div>


{% endblock %}

users/templates/users/registration_email_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Письмо успешно отправлено</div>

        </div>
    </div>

    </div>
</body>
</html>